// ESSA FUNÇÃO RECEBE TRÊS PARÂMETROS:
// O PRIMEIRO DIZ SE O LED DEVE SER ACESO OU APAGADO
// O SEGUNDO DIZ QUAL A LAYER DO LED EM QUESTÃO
// O TERCEIRO DIZ AS COORDENADAS DO BOTÃO CLICADO
// A FUNÇÃO ENTÃO RETORNA UMA MENSAGEM NO FORMATO STRING QUE SERÁ ESCRITA NA PORTA SERIAL PARA SER INTERPRETADA PELO CHIPKIT
String dataSent(int state, int layerNumber, int index){
  String v = ",";
  String data = state + v + layerNumber + v + index;
  return data;
}
